import type { Metadata } from "next";
import "@/app/assets/styles/globals.css";
import { Roboto } from "next/font/google";
import Header from "@/components/header/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import Sidebar from "@/components/sidebar/Sidebar";
import Footer from "@/components/footer/Footer";
import Widget from "@/components/widget/Widget";
import { cn } from "@/lib/utils";
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn("dark:bg-black bg-white", roboto.className)}>
        <ThemeProvider attribute='class' disableTransitionOnChange>
          <Header />
          <main className='flex'>
            <Sidebar />
            <div className='flex justify-between w-full  px-[30px] border-l border-[var(--border-color)]'>
              {children}
              <Widget />
            </div>
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
