export const languages = [
  { value: "/intl/af/docs/about/", label: "Afrikaans" },
  { value: "/intl/en/docs/about/", label: "English" },
  { value: "/intl/am/docs/about/", label: "አማርኛ" },
  { value: "/intl/ar/docs/about/", label: "العربية" },
  { value: "/intl/az/docs/about/", label: "azərbaycan" },
  { value: "/intl/bg/docs/about/", label: "български" },
  { value: "/intl/bn/docs/about/", label: "বাংলা" },
  { value: "/intl/ca/docs/about/", label: "català" },
  { value: "/intl/cs/docs/about/", label: "čeština" },
  { value: "/intl/da/docs/about/", label: "dansk" },
  { value: "/intl/de/docs/about/", label: "Deutsch" },
  { value: "/intl/el/docs/about/", label: "Ελληνικά" },
  { value: "/intl/en-GB/docs/about/", label: "English (United Kingdom)" },
  { value: "/intl/es-419/docs/about/", label: "español (Latinoamérica)" },
  { value: "/intl/es/docs/about/", label: "español" },
  { value: "/intl/et/docs/about/", label: "eesti" },
  { value: "/intl/eu/docs/about/", label: "euskara" },
  { value: "/intl/fa/docs/about/", label: "فارسی" },
  { value: "/intl/fi/docs/about/", label: "suomi" },
  { value: "/intl/fil/docs/about/", label: "Filipino" },
  { value: "/intl/fr-CA/docs/about/", label: "français (Canada)" },
  { value: "/intl/fr/docs/about/", label: "français" },
  { value: "/intl/gl/docs/about/", label: "galego" },
  { value: "/intl/gu/docs/about/", label: "ગુજરાતી" },
  { value: "/intl/hi/docs/about/", label: "हिन्दी" },
  { value: "/intl/hr/docs/about/", label: "hrvatski" },
  { value: "/intl/hu/docs/about/", label: "magyar" },
  { value: "/intl/hy/docs/about/", label: "հայերեն" },
  { value: "/intl/id/docs/about/", label: "Indonesia" },
  { value: "/intl/is/docs/about/", label: "íslenska" },
  { value: "/intl/it/docs/about/", label: "italiano" },
  { value: "/intl/iw/docs/about/", label: "עברית (ישראל)" },
  { value: "/intl/ja/docs/about/", label: "日本語" },
  { value: "/intl/ka/docs/about/", label: "ქართული" },
  { value: "/intl/km/docs/about/", label: "ខ្មែរ" },
  { value: "/intl/kn/docs/about/", label: "ಕನ್ನಡ" },
  { value: "/intl/ko/docs/about/", label: "한국어" },
  { value: "/intl/lo/docs/about/", label: "ລາວ" },
  { value: "/intl/lt/docs/about/", label: "lietuvių" },
  { value: "/intl/lv/docs/about/", label: "latviešu" },
  { value: "/intl/ml/docs/about/", label: "മലയാളം" },
  { value: "/intl/mn/docs/about/", label: "монгол" },
  { value: "/intl/mr/docs/about/", label: "मराठी" },
  { value: "/intl/ms/docs/about/", label: "Melayu" },
  { value: "/intl/ne/docs/about/", label: "नेपाली" },
  { value: "/intl/nl/docs/about/", label: "Nederlands" },
  { value: "/intl/no/docs/about/", label: "norsk bokmål (Norge)" },
  { value: "/intl/pl/docs/about/", label: "polski" },
  { value: "/intl/pt-BR/docs/about/", label: "português (Brasil)" },
  { value: "/intl/pt-PT/docs/about/", label: "português (Portugal)" },
  { value: "/intl/ro/docs/about/", label: "română" },
  { value: "/intl/ru/docs/about/", label: "русский" },
  { value: "/intl/si/docs/about/", label: "සිංහල" },
  { value: "/intl/sk/docs/about/", label: "slovenčina" },
  { value: "/intl/sl/docs/about/", label: "slovenščina" },
  { value: "/intl/sr/docs/about/", label: "српски" },
  { value: "/intl/sv/docs/about/", label: "svenska" },
  { value: "/intl/sw/docs/about/", label: "Kiswahili" },
  { value: "/intl/ta/docs/about/", label: "தமிழ்" },
  { value: "/intl/te/docs/about/", label: "తెలుగు" },
  { value: "/intl/th/docs/about/", label: "ไทย" },
  { value: "/intl/tr/docs/about/", label: "Türkçe" },
  { value: "/intl/uk/docs/about/", label: "українська" },
  { value: "/intl/ur/docs/about/", label: "اردو" },
  { value: "/intl/vi/docs/about/", label: "Tiếng Việt" },
  { value: "/intl/zh-CN/docs/about/", label: "中文 (简体)" },
  { value: "/intl/zh-HK/docs/about/", label: "中文" },
  { value: "/intl/zh-TW/docs/about/", label: "中文 (繁體)" },
  { value: "/intl/zu/docs/about/", label: "isiZulu" },
];
